version: "3.7"
services:
  auth-service:
    build: ./auth
    environment:
      JWT_SECRET_KEY: myawesomeultrasecretkey
      JWT_ISSUER: student
      JWT_SUBJECT: 'Token pentru laboratorul 6'
      JWT_AUDIENCE: postman
      NODE_ENV: dev
      PORT: 80
      MHOST: mongo
      MPORT: 27017
      MDATABASE: testdb
      MUSER: student
      MPASSWORD: student
    ports:
      - "3000:80"
    networks:
      - main
    depends_on:
      - mongo

  api-service:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      AUTH_SERVICE_API_ROUTE: auth-service/api/v1/users
      NODE_ENV: dev
      PORT1: 3001
      MHOST: mongo
      MPORT: 27017
      MDATABASE: testdb
      MUSER: student
      MPASSWORD: student
    networks:
      - main
    depends_on:
      - mongo

  messages-service:
    build: ./messages
    ports:
      - "3002:3002"
    environment:
      AUTH_SERVICE_API_ROUTE: auth-service/api/v1/users
      NODE_ENV: dev
      PORT2: 3002
      MHOST: mongo
      MPORT: 27017
      MDATABASE: testdb
      MUSER: student
      MPASSWORD: student
    networks:
      - main
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: testdb
      MONGO_INITDB_ROOT_USERNAME: student
      MONGO_INITDB_ROOT_PASSWORD: student
    expose:
      - "27017"
    volumes:
      - lab6_data:/data/db
    networks:
      - main

  mongo-express:
    image: mongo-express
    ports:
      - 9081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: student
      ME_CONFIG_MONGODB_ADMINPASSWORD: student
    logging:
      driver: none
    networks:
      - main

volumes:
  lab6_data:

networks:
  main:
    driver: bridge
