version: "3.7"
services:
  auth-service:
    image: dianabrodoceanu/proiect-cc-auth-v1:kong
    environment:
      JWT_SECRET_KEY: myawesomeultrasecretkey
      JWT_ISSUER: student
      JWT_SUBJECT: 'Token pentru laboratorul 6'
      JWT_AUDIENCE: postman
      NODE_ENV: dev
      MHOST: mongo
      MPORT: 27017
      MDATABASE: testdb
      MUSER: student
      MPASSWORD: student
    networks:
      - main
    depends_on:
      - mongo

  api-service:
    image: dianabrodoceanu/proiect-cc-api-v1:kong
    environment:
      AUTH_SERVICE_API_ROUTE: proiect-cluster_auth-service/api/v1/users
      NODE_ENV: dev
      MHOST: mongo
      MPORT: 27017
      MDATABASE: testdb
      MUSER: student
      MPASSWORD: student
    networks:
      - main
    depends_on:
      - mongo

  messages-service:
    image: dianabrodoceanu/proiect-cc-messages-v1:kong
    environment:
      AUTH_SERVICE_API_ROUTE: proiect-cluster_auth-service/api/v1/users
      NODE_ENV: dev
      MHOST: mongo
      MPORT: 27017
      MDATABASE: testdb
      MUSER: student
      MPASSWORD: student
    networks:
      - main
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: testdb
      MONGO_INITDB_ROOT_USERNAME: student
      MONGO_INITDB_ROOT_PASSWORD: student
    volumes:
      - lab6_data:/data/db
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - main

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: student
      ME_CONFIG_MONGODB_ADMINPASSWORD: student
    logging:
      driver: none
    networks:
      - main

  kong:
    image: kong:latest
    volumes:
      - ./kong:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 80:8000
      - 443:8443
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - main

volumes:
  lab6_data:

networks:
  main:
    driver: overlay
